server:
  port: 12000
  servlet:
    context-path: /
logging:
  level:
    .: info
    cn.lhfei.monitor: debug
    cn.lhfei.monitor.orm.mapper: debug
    org.springframework: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"


# Druid datasource settings:
spring:
  datasource:
    url: jdbc:mysql://192.168.133.159:3306/monitor_admin?useSSL=false
    username: monitor
    password: NxMonitor_1473
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  kafka:
    consumer:
      group-id: test
      auto-offset-reset: earliest
    # change this property if you are using your own
    # Kafka cluster or your Docker IP is different
    #bootstrap-servers: 192.168.134.92:9092
    bootstrap-servers: 192.168.135.120:9092,192.168.135.231:9092,192.168.135.255:9092

canal:
  config:
    address: 127.0.0.1
    port: 11111
    username:
    password:
    destination: my-db
    subscribe: test.user
    batchSize: 1000
  kafka:
    topic: example
    group-id: test
    bootstrap-servers: host-192-168-136-15:9092,host-192-168-136-16:9092,host-192-168-136-144:9092
    zk-servers: host-192-168-136-15:2181, host-192-168-136-16:2181,host-192-168-136-144:2181

swagger:
  enabled: true
  
mybatis:
  type-aliases-package: cn.lhfei.monitor.orm.domain
  
