server:
  port: 12000
  servlet:
    context-path: /
logging:
  level:
    .: info
    cn.lhfei.monitor: info
    cn.lhfei.monitor.orm.mapper: info
    org.springframework: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    max-size: 2048M
      

# Druid datasource settings:
spring:
  datasource:
    #url: jdbc:mysql://192.168.133.159:3306/monitor_admin?useSSL=false
    url: jdbc:mysql://10.217.7.116:13306/monitor_admin?useSSL=false
    username: monitor
    password: NxMonitor_1473
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  kafka:
    consumer:
      group-id: test
      auto-offset-reset: earliest
    # change this property if you are using your own
    # Kafka cluster or your Docker IP is different
    #bootstrap-servers: 10.216.169.156:9192
    bootstrap-servers: 192.168.111.226:9092,192.168.111.229:9092,192.168.111.228:9092

  
mybatis:
  type-aliases-package: cn.lhfei.monitor.orm.domain
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations:
  - classpath:/mybatis/mappers/OpsLogMapper.xml
  - classpath:/mybatis/mappers/ModuleMapper.xml

swagger:
  enabled: true 
